# Install with brew bundle install --global

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "teamookla/speedtest"
tap "homebrew/cask-fonts"

brew "awscli"
brew "bat"
brew "ctags"
brew "fzf"
brew "gcc"
brew "git"
brew "git-gui"
brew "htop"
brew "imagemagick"
brew "jq"
brew "neovim"
brew "pandoc"
brew "pympress"
brew "python@3.13"
brew "ripgrep"
brew "sshuttle"
brew "teamookla/speedtest/speedtest"
brew "tig"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "watch"
brew "wget"
brew "yq"
brew "zsh"
cask "font-fira-code"
cask "iterm2"
cask "mactex"
cask "visual-studio-code"
cask "zed"
