#!/usr/bin/env ruby

require 'colorize'

###
# Creates symlinks for all files in ~/.dotfiles

puts "Making symling for dotfiles...".green

# these files won't be symlinked.
blacklist = [File.basename(__FILE__), 'README.md']

homedir = ENV['HOME']
dotfilesdir = "#{homedir}/.dotfiles"

Dir.foreach(dotfilesdir) do |filename|

  # skip dotfiles (.gitignore, .gitmodules...)
  next if filename =~ /^\..*/

  # skip blacklisted files
  next if blacklist.include? filename
  
  # create the symlinks, overriding any existing links/files.
  from  = "#{dotfilesdir}/#{filename}"
  to    = "#{homedir}/.#{filename}"
  just = dotfilesdir.length + 26;

  print "Linking #{from}".ljust(just).light_green
  print "->"
  print "#{to}... ".rjust(just-6).light_green

  res = system "ln -snFf #{from} #{to}"
  puts "#{res ? "OK".green : "ERROR (#{$?.exitstatus})".red}"

end
