# This env installs some python codestyle tools
name: py-codestyle
channels:
  - conda-forge
dependencies:
  - black-jupyter
  - isort
  - mypy
  - pip
  - pylsp-mypy
  - python
  - python-lsp-black
  - python-lsp-ruff
  - python-lsp-server
  - ruff
