#!/usr/bin/env ruby

require 'colorize'

###
# Creates tag file for currently selected ruby and gemset.
# inspired by http://www.elonflegenheimer.com/2012/09/16/navigating-ruby-projects-in-vim.html
# but this script accounts for the RVM gemsets.

# read rvm environment
rvm_current = `rvm current`.chomp

# get the ruby version string and gemset name if applicable
if rvm_current =~ /@/
  m = /(.+)@(.*)/.match rvm_current
  ruby_ver = m[1]
  ruby_gemset = m[2]
else
  ruby_ver = rvm_current
end

print "Creating tags for #{rvm_current}... ".green

# input directories for ctags
rvm_gemdir = "#{ENV['HOME']}/.rvm/gems/#{rvm_current}/gems"
rvm_rubydir = "#{ENV['HOME']}/.rvm/rubies/#{ruby_ver}"

# output tag file name
tagfile = "#{ENV['HOME']}/.vim/tags/#{rvm_current}"
tags_dir = File.dirname tagfile
Dir.mkdir tags_dir unless Dir.exist? tags_dir

# run ctags to generate the tags
excludes = "--exclude=.git --exclude=tags --exclude=logs --exclude=doc"
res = system "ctags #{excludes} -R -f #{tagfile} #{rvm_rubydir} #{rvm_gemdir}"

# results
if res
  puts "Success.".green
  puts "Created tags file: #{tagfile}"
else
  puts "ERROR. (#{$?.exitstatus})".red
end
