# zsh startup file order:
# https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/
# On macOS, the /etc/zprofile mofifies the PATH after ~/.zshenv by running
# /usr/libexec/path_helper. See:
# 1. https://mattprice.me/2015/zsh-path-issues-osx-el-capitan/
# 2. http://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper.
# +----------------+-----------+-----------+------+
# |                |Interactive|Interactive|Script|
# |                |login      |non-login  |      |
# +----------------+-----------+-----------+------+
# |/etc/zshenv     |    A      |    A      |  A   |
# +----------------+-----------+-----------+------+
# |~/.zshenv       |    B      |    B      |  B   |
# +----------------+-----------+-----------+------+
# |/etc/zprofile   |    C      |           |      | <-- Modifies PATH on macOS
# +----------------+-----------+-----------+------+
# |~/.zprofile     |    D      |           |      |
# +----------------+-----------+-----------+------+
# |/etc/zshrc      |    E      |    C      |      |
# +----------------+-----------+-----------+------+
# |~/.zshrc        |    F      |    D      |      |
# +----------------+-----------+-----------+------+
# |/etc/zlogin     |    G      |           |      |
# +----------------+-----------+-----------+------+
# |~/.zlogin       |    H      |           |      |
# +----------------+-----------+-----------+------+
# |~/.zlogout      |    I      |           |      |
# +----------------+-----------+-----------+------+
# |/etc/zlogout    |    J      |           |      |
# +----------------+-----------+-----------+------+

####
## Environment
export EDITOR='nvim'
export DOTFILES="$HOME/.dotfiles"
export LESS='-R -S'
export PAGER='less -RSFX'
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
export BAT_PAGER='less'
export BAT_THEME='Solarized (dark)'
export XDG_CONFIG_HOME="$HOME/.config"

###
## conda/mamba
# Custom init script based on `conda/mamba init`.
# This needs to be in zshenv so that conda/mamba is available in all shells
# (interactive login, interactive non-login, and scripts).
source "$DOTFILES/conda/conda_init.sh"
