###
## zsh
export ZSH="$DOTFILES/zsh/oh-my-zsh"
# directory with custom zsh init scripts
ZSH_CUSTOM=~/.dotfiles/zsh
# set plugins for oh-my-zsh
plugins=(git macos brew tmuxinator iterm2 themes docker python conda-zsh-completion zsh-syntax-highlighting)
# set theme for oh-my-zsh
ZSH_THEME="kphoen"
# load oh-my-zsh
source $ZSH/oh-my-zsh.sh
# Enable zmv command
autoload -U zmv
#
# These vars were set in my zshenv but for some reason get overwritten by OMZ...
export LESS='-R -S'
export PAGER='less -RSFX'

### Custom shell settings
# Map C-N and C-P to search history (like up/down)
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

###
## Homebrew
if [[ -x "/opt/homebrew/bin/brew" ]]; then
    # Adds homebrew to PATH
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi


###
## FZF
# Default options are in ~/.fzfrc (via FZF_DEFAULT_OPTS_FILE set in zshenv)
if [[ -x "$(which brew 2>/dev/null)" && -d "$(brew --prefix fzf)" ]]; then
  FZF_DIR="$(brew --prefix fzf)"

  # Use ripgrep if fzf invoked without command
  if [[ -x "$(which rg 2>/dev/null)" ]]; then
    export FZF_DEFAULT_COMMAND='rg --files'
  fi

  # Auto-completion
  [[ $- == *i* ]] && source "$FZF_DIR/shell/completion.zsh" 2> /dev/null

  # Key bindings (provides Ctrl-T, Ctrl-R, Alt-C)
  source "$FZF_DIR/shell/key-bindings.zsh"
fi

###
## 1Password SSH Agent
# https://developer.1password.com/docs/ssh/
OP_SSH_AGENT_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
OP_HOME="$HOME/.1password"
if [[ -S "${OP_SSH_AGENT_SOCK}" ]]; then
  mkdir -p "${OP_HOME}"
  ln -f -s "${OP_SSH_AGENT_SOCK}" "${OP_HOME}/agent.sock"
fi


###
## Custom binaries and scripts
PATH=$PATH:"$HOME/.bin/"
PATH=$PATH:"$HOME/.local/bin/"

###
# Adds rust toolchain to PATH
if [[ -f "$HOME/.cargo/env" ]]; then
    . "$HOME/.cargo/env"
fi

###
# prevent duplicates in PATH: the zsh 'path' variable is an array and mirrors
# PATH, setting it to unique removes duplicate entries.
typeset -aU path
export PATH

# The next line updates PATH for Nebius CLI.
if [ -f '/Users/avivr/.nebius/path.zsh.inc' ]; then source '/Users/avivr/.nebius/path.zsh.inc'; fi
